"use client";

import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ja" | "ko" | "en";

const labels: Record<Language, Record<string, string>> = {
  ja: {
    brand: "レシピ広場",
    recommended: "おすすめ",
    categories: "カテゴリー",
    ranking: "ランキング",
    column: "コラム",
    post: "レシピ投稿",
    mypage: "マイページ",
    searchPlaceholder: "料理名・食材で検索",
    login: "ログイン",
    signup: "会員登録",
    logout: "ログアウト",
    recipes: "レシピ",
    recipeList: "レシピ一覧",
    recipeSearch: "レシピ検索",
    more: "もっと見る",
    search: "検索",
    welcome: "Welcome",
    heroKicker: "毎日のごはんを、もっと楽しく",
    heroTitle: "今日なに作る？",
    heroDescription: "家庭料理・時短料理・お弁当・スイーツまで探せる、みんなで育てるレシピコミュニティです。",
    todayPick: "今日のおすすめ",
    recommendedRecipes: "おすすめレシピ",
    bestRecipes: "ベストレシピ",
    popular: "人気",
    todayPopularRecipes: "今日の人気レシピ",
    todayAccessRanking: "今日のアクセスランキング",
    categorySearchTitle: "料理ジャンルから探す",
    creator: "クリエイター",
    popularCreators: "人気の投稿者",
    easyFeature: "簡単料理特集",
    quickFeatureTitle: "10〜20分で作れる、忙しい日のごはん",
    quickFeatureDescription: "一人暮らし、仕事帰り、朝ごはんにも使いやすい時短レシピをまとめました。",
    quickFeatureButton: "時短レシピを見る",
    themedSearch: "テーマで探す",
    themeTitle: "今の気分に合うレシピ",
    themeBento: "お弁当",
    themeBentoDesc: "冷めてもおいしい作り置きと主菜",
    themeSolo: "一人暮らし",
    themeSoloDesc: "少ない材料で作れる気軽なごはん",
    themeHealthy: "ヘルシー",
    themeHealthyDesc: "野菜とたんぱく質をしっかり取れる料理",
    themeSweets: "おやつ",
    themeSweetsDesc: "週末に作りたい簡単スイーツ",
    guide: "ガイド",
    guideTitle: "料理のヒント",
    guideOne: "失敗しにくい下ごしらえ",
    guideTwo: "残り物で作る献立",
    guideThree: "人気投稿の伸ばし方",
    latest: "新着",
    latestRecipes: "新着レシピ",
    expertMagazine: "専門家マガジン",
    magazineOne: "旬の野菜をおいしく使い切るコツ",
    magazineTwo: "だしを変えるだけで広がる和食の味",
    magazineThree: "忙しい日のための作り置き設計",
    magazineFour: "お米をもっとおいしく炊く基本",
    loadedRecipes: "投稿レシピを読み込み中です。",
    loadRecipesFailed: "投稿レシピを読み込めませんでした。",
    recipesFoundSuffix: "件のレシピ",
    noRecipesTitle: "該当するレシピが見つかりませんでした。",
    noRecipesText: "別のキーワードで検索してください。",
    categoryDescription: "和食、時短料理、スイーツ、作り置きなど、目的に合わせてレシピを探せます。",
    rankingTitle: "人気レシピランキング",
    rankingDescription: "閲覧数、いいね、保存数から人気レシピを確認できます。",
    viewsRanking: "閲覧数ランキング",
    likesRanking: "いいねランキング",
    savesRanking: "保存数ランキング",
    weeklyPopular: "今週の人気レシピ",
    newestPopular: "新着人気レシピ",
    views: "閲覧",
    likes: "いいね",
    saves: "保存",
    minutes: "分",
    people: "人分",
    loading: "読み込み中...",
    loginRequired: "ログインが必要です",
    loginRequiredPost: "レシピを投稿するには、会員登録またはログインしてください。",
    loginRequiredMypage: "ポイントと投稿管理を見るにはログインしてください。",
    goLogin: "ログインへ",
    myPage: "マイページ",
    myPageLoading: "マイページを読み込んでいます。",
    roleAdmin: "運営者",
    pointsOwned: "保有ポイント",
    pointHistory: "ポイント履歴",
    noPointHistory: "まだポイント履歴がありません。",
    pointSignup: "会員登録ボーナス",
    pointRecipePost: "レシピ投稿ポイント",
    pointLikeMilestone: "いいね達成ポイント",
    myRecipes: "自分の投稿",
    newPost: "新規投稿",
    edit: "編集",
    delete: "削除",
    deleteConfirm: "このレシピを削除しますか？",
    noMyRecipes: "まだ投稿がありません。",
    firstRecipePost: "最初のレシピを投稿",
    adminPanel: "運営者ポイント管理",
    adminPanelDesc: "自分や他の会員にポイントを付与・差し引きできます。",
    targetUser: "対象ユーザー",
    pointAmount: "ポイント数",
    pointReason: "理由",
    pointReasonPlaceholder: "例：イベント報酬、運営調整",
    applyPoint: "ポイント反映",
    pointAdjustSuccess: "ポイントを反映しました。",
    pointAdjustFailed: "ポイントを反映できませんでした。",
    usersLoading: "ユーザーを読み込んでいます。",
    currentUser: "自分",
    basicInfo: "基本情報",
    recipeEdit: "レシピ編集",
    title: "タイトル",
    titlePlaceholder: "例：ふわとろ親子丼",
    mainImage: "代表画像",
    imageUrlPlaceholder: "画像URLを入力",
    imageNotice: "写真ファイルの直接アップロードはFirebase Storage有料設定後に使えます。今は画像URLで登録してください。",
    description: "説明",
    descriptionPlaceholder: "レシピの紹介文を入力してください",
    cookingTime: "調理時間",
    servings: "人数",
    difficulty: "難易度",
    category: "カテゴリー",
    ingredients: "材料",
    addIngredient: "材料追加",
    ingredientName: "材料名",
    ingredientAmount: "分量",
    steps: "作り方",
    addStep: "手順追加",
    stepPlaceholder: "調理手順を入力",
    tagsTips: "タグ・補足",
    tags: "タグ",
    tagsPlaceholder: "例：時短, 和食, お弁当",
    tips: "コツ・ポイント",
    tipsPlaceholder: "おいしく作るためのコツを書いてください",
    submit: "登録する",
    update: "更新する",
    formNeedItems: "材料と作り方を1つ以上入力してください。",
    formPostFailed: "レシピを投稿できませんでした。",
    formLoadRecipe: "レシピを読み込んでいます。",
    formCheckLogin: "ログイン状態を確認しています。",
    formOnlyMine: "自分のレシピだけ編集できます。",
    formLoadFailed: "編集するレシピを読み込めませんでした。",
    authorDefault: "料理好きユーザー",
    authorBioDefault: "レシピ広場の投稿者です。",
    tipsDefault: "作りやすい分量に調整しながら楽しんでください。",
    loginHeroTitle: "レシピ広場で、毎日の料理をもっと楽しく。",
    loginHeroDesc: "お気に入りレシピの保存、投稿、コメント機能を使うにはログインしてください。",
    accountFeatures: "アカウント機能",
    accountFeaturesDesc: "メールアドレスとパスワードでログインできます。",
    loggedIn: "ログイン中です",
    backHome: "トップへ戻る",
    nickname: "ニックネーム",
    email: "メールアドレス",
    password: "パスワード",
    passwordMin: "6文字以上",
    passwordConfirm: "パスワード確認",
    passwordConfirmPlaceholder: "もう一度入力",
    recoveryQuestion: "本人確認の質問",
    recoveryAnswer: "質問の答え",
    recoveryAnswerPlaceholder: "答えを入力",
    signupButton: "会員登録する",
    loginButton: "ログインする",
    forgotPassword: "パスワードを忘れた場合",
    resetEmailPlaceholder: "登録メールアドレス",
    resetNotice: "本人確認の質問は運営確認用に保存されます。実際の再設定リンクは登録メールへ送信されます。",
    sendReset: "再設定メールを送る",
    noAccountGuide: "アカウントをお持ちでない方は「会員登録」から始められます。",
    hasAccountGuide: "登録済みの方は「ログイン」へ切り替えてください。",
    nameTooShort: "ニックネームは2文字以上入力してください。",
    passwordMismatch: "パスワードが一致しません。もう一度入力してください。",
    recoveryRequired: "本人確認の答えを入力してください。",
    signupDone: "会員登録が完了しました。",
    loginDone: "ログインしました。",
    resetSent: "パスワード再設定メールを送りました。メールを確認してください。",
    firebaseRequired: "Firebase設定が必要です。設定値を確認してからもう一度試してください。",
    categoryCountSuffix: "件のレシピ",
    shareCopied: "URLをコピーしました",
    save: "保存",
    share: "共有",
    manageDelete: "削除",
    banAuthor: "投稿者をBAN",
    banConfirm: "この投稿者の利用を制限しますか？",
    banDone: "投稿者を利用制限にしました。",
    recipeIngredients: "材料",
    recipeSteps: "作り方",
    cookingTips: "おいしく作るコツ",
    comments: "コメント",
    commentsLoading: "コメントを読み込み中です。",
    firstComment: "最初のコメントを書いてみましょう。",
    commentPlaceholder: "コメントを書く",
    commentLoginPlaceholder: "ログインするとコメントできます",
    commentSubmit: "コメント投稿",
    relatedRecipes: "関連レシピ",
    footerDescription: "毎日の料理をもっと楽しく。家庭料理、時短料理、人気レシピを探せるコミュニティです。",
    footerFind: "探す",
    footerJoin: "参加する",
    footerConcept: "コンセプト",
    footerConceptText: "日本の食卓に合う、あたたかくて使いやすいレシピ体験を目指しています。",
    postPageTitle: "あなたのレシピを投稿する",
    postPageDesc: "家庭の定番料理、時短レシピ、アレンジ料理などをレシピ広場に投稿しましょう。",
    formLoading: "フォームを読み込んでいます。",
    recipeLoading: "レシピを読み込んでいます。",
    recipeNotFound: "レシピが見つかりません",
    recipeNotFoundDesc: "削除されたか、URLが間違っている可能性があります。",
    goRecipeList: "レシピ一覧へ",
  },
  ko: {
    brand: "요리히로바",
    recommended: "추천",
    categories: "카테고리",
    ranking: "랭킹",
    column: "칼럼",
    post: "레시피 등록",
    mypage: "마이페이지",
    searchPlaceholder: "요리명・재료 검색",
    login: "로그인",
    signup: "회원가입",
    logout: "로그아웃",
    recipes: "레시피",
    recipeList: "레시피 목록",
    recipeSearch: "레시피 검색",
    more: "더 보기",
    search: "검색",
    welcome: "환영합니다",
    heroKicker: "매일의 식사를 더 즐겁게",
    heroTitle: "오늘 뭐 만들까요?",
    heroDescription: "가정식, 간단 요리, 도시락, 디저트까지 함께 찾고 올리는 레시피 커뮤니티입니다.",
    todayPick: "오늘의 추천",
    recommendedRecipes: "추천 레시피",
    bestRecipes: "베스트 레시피",
    popular: "인기",
    todayPopularRecipes: "오늘의 인기 레시피",
    todayAccessRanking: "오늘의 조회 랭킹",
    categorySearchTitle: "요리 장르로 찾기",
    creator: "크리에이터",
    popularCreators: "인기 작성자",
    easyFeature: "간단 요리 특집",
    quickFeatureTitle: "10~20분 안에 만드는 바쁜 날의 한 끼",
    quickFeatureDescription: "혼밥, 퇴근 후 식사, 아침밥에도 쓰기 좋은 빠른 레시피를 모았습니다.",
    quickFeatureButton: "간단 레시피 보기",
    themedSearch: "테마로 찾기",
    themeTitle: "지금 기분에 맞는 레시피",
    themeBento: "도시락",
    themeBentoDesc: "식어도 맛있는 밑반찬과 메인 요리",
    themeSolo: "혼밥",
    themeSoloDesc: "적은 재료로 만드는 부담 없는 식사",
    themeHealthy: "건강식",
    themeHealthyDesc: "채소와 단백질을 챙기는 요리",
    themeSweets: "간식",
    themeSweetsDesc: "주말에 만들기 좋은 쉬운 디저트",
    guide: "가이드",
    guideTitle: "요리 힌트",
    guideOne: "실패를 줄이는 손질법",
    guideTwo: "남은 재료로 만드는 식단",
    guideThree: "인기 게시글을 키우는 법",
    latest: "신규",
    latestRecipes: "신규 레시피",
    expertMagazine: "전문가 매거진",
    magazineOne: "제철 채소를 맛있게 쓰는 팁",
    magazineTwo: "다시만 바꿔도 달라지는 와쇼쿠 맛",
    magazineThree: "바쁜 날을 위한 밑반찬 설계",
    magazineFour: "밥을 더 맛있게 짓는 기본",
    loadedRecipes: "게시 레시피를 불러오는 중입니다.",
    loadRecipesFailed: "게시 레시피를 불러오지 못했습니다.",
    recipesFoundSuffix: "개의 레시피",
    noRecipesTitle: "해당하는 레시피를 찾지 못했습니다.",
    noRecipesText: "다른 키워드로 검색해보세요.",
    categoryDescription: "와쇼쿠, 간단 요리, 디저트, 밑반찬 등 목적에 맞게 레시피를 찾을 수 있습니다.",
    rankingTitle: "인기 레시피 랭킹",
    rankingDescription: "조회수, 좋아요, 저장 수 기준으로 인기 레시피를 확인할 수 있습니다.",
    viewsRanking: "조회수 랭킹",
    likesRanking: "좋아요 랭킹",
    savesRanking: "저장 랭킹",
    weeklyPopular: "이번 주 인기 레시피",
    newestPopular: "신규 인기 레시피",
    views: "조회",
    likes: "좋아요",
    saves: "저장",
    minutes: "분",
    people: "인분",
    loading: "불러오는 중...",
    loginRequired: "로그인이 필요합니다",
    loginRequiredPost: "레시피를 등록하려면 회원가입 또는 로그인을 해주세요.",
    loginRequiredMypage: "포인트와 게시글 관리를 보려면 로그인해주세요.",
    goLogin: "로그인하러 가기",
    myPage: "마이페이지",
    myPageLoading: "마이페이지를 불러오는 중입니다.",
    roleAdmin: "운영자",
    pointsOwned: "보유 포인트",
    pointHistory: "포인트 내역",
    noPointHistory: "아직 포인트 내역이 없습니다.",
    pointSignup: "회원가입 보너스",
    pointRecipePost: "레시피 등록 포인트",
    pointLikeMilestone: "좋아요 달성 포인트",
    myRecipes: "내 게시글",
    newPost: "새 글 작성",
    edit: "수정",
    delete: "삭제",
    deleteConfirm: "이 레시피를 삭제할까요?",
    noMyRecipes: "아직 게시글이 없습니다.",
    firstRecipePost: "첫 레시피 등록하기",
    adminPanel: "운영자 포인트 관리",
    adminPanelDesc: "내 계정이나 다른 회원에게 포인트를 지급하거나 차감할 수 있습니다.",
    targetUser: "대상 회원",
    pointAmount: "포인트 수",
    pointReason: "사유",
    pointReasonPlaceholder: "예: 이벤트 보상, 운영 조정",
    applyPoint: "포인트 반영",
    pointAdjustSuccess: "포인트를 반영했습니다.",
    pointAdjustFailed: "포인트를 반영하지 못했습니다.",
    usersLoading: "회원을 불러오는 중입니다.",
    currentUser: "나",
    basicInfo: "기본 정보",
    recipeEdit: "레시피 수정",
    title: "제목",
    titlePlaceholder: "예: 부드러운 오야코동",
    mainImage: "대표 이미지",
    imageUrlPlaceholder: "이미지 URL 입력",
    imageNotice: "사진 파일 직접 업로드는 Firebase Storage 유료 설정 후 사용할 수 있습니다. 지금은 이미지 URL로 등록해주세요.",
    description: "설명",
    descriptionPlaceholder: "레시피 소개를 입력해주세요",
    cookingTime: "조리 시간",
    servings: "인원",
    difficulty: "난이도",
    category: "카테고리",
    ingredients: "재료",
    addIngredient: "재료 추가",
    ingredientName: "재료명",
    ingredientAmount: "분량",
    steps: "만드는 법",
    addStep: "순서 추가",
    stepPlaceholder: "조리 순서를 입력",
    tagsTips: "태그・보충",
    tags: "태그",
    tagsPlaceholder: "예: 간단, 와쇼쿠, 도시락",
    tips: "팁・포인트",
    tipsPlaceholder: "맛있게 만드는 팁을 적어주세요",
    submit: "등록하기",
    update: "수정하기",
    formNeedItems: "재료와 만드는 법을 1개 이상 입력해주세요.",
    formPostFailed: "레시피를 등록하지 못했습니다.",
    formLoadRecipe: "레시피를 불러오는 중입니다.",
    formCheckLogin: "로그인 상태를 확인하는 중입니다.",
    formOnlyMine: "내 레시피만 수정할 수 있습니다.",
    formLoadFailed: "수정할 레시피를 불러오지 못했습니다.",
    authorDefault: "요리를 좋아하는 유저",
    authorBioDefault: "요리히로바의 작성자입니다.",
    tipsDefault: "만들기 쉬운 분량으로 조절하면서 즐겨주세요.",
    loginHeroTitle: "요리히로바에서 매일의 요리를 더 즐겁게.",
    loginHeroDesc: "즐겨찾기, 레시피 등록, 댓글 기능을 사용하려면 로그인해주세요.",
    accountFeatures: "계정 기능",
    accountFeaturesDesc: "이메일과 비밀번호로 로그인할 수 있습니다.",
    loggedIn: "로그인 중입니다",
    backHome: "홈으로 돌아가기",
    nickname: "닉네임",
    email: "이메일 주소",
    password: "비밀번호",
    passwordMin: "6자 이상",
    passwordConfirm: "비밀번호 확인",
    passwordConfirmPlaceholder: "한 번 더 입력",
    recoveryQuestion: "본인 확인 질문",
    recoveryAnswer: "질문 답변",
    recoveryAnswerPlaceholder: "답변을 입력",
    signupButton: "회원가입하기",
    loginButton: "로그인하기",
    forgotPassword: "비밀번호를 잊으셨나요?",
    resetEmailPlaceholder: "가입 이메일 주소",
    resetNotice: "본인 확인 질문은 운영 확인용으로 저장됩니다. 실제 재설정 링크는 가입 이메일로 전송됩니다.",
    sendReset: "재설정 메일 보내기",
    noAccountGuide: "계정이 없다면 회원가입에서 시작할 수 있습니다.",
    hasAccountGuide: "이미 가입했다면 로그인으로 전환해주세요.",
    nameTooShort: "닉네임은 2자 이상 입력해주세요.",
    passwordMismatch: "비밀번호가 일치하지 않습니다. 다시 입력해주세요.",
    recoveryRequired: "본인 확인 질문의 답을 입력해주세요.",
    signupDone: "회원가입이 완료되었습니다.",
    loginDone: "로그인되었습니다.",
    resetSent: "비밀번호 재설정 이메일을 보냈습니다. 메일함을 확인해주세요.",
    firebaseRequired: "Firebase 설정이 필요합니다. 설정값을 확인한 뒤 다시 시도해주세요.",
    categoryCountSuffix: "개의 레시피",
    shareCopied: "URL을 복사했습니다",
    save: "저장",
    share: "공유",
    manageDelete: "삭제",
    banAuthor: "작성자 BAN",
    banConfirm: "이 작성자의 이용을 제한할까요?",
    banDone: "작성자를 이용 제한했습니다.",
    recipeIngredients: "재료",
    recipeSteps: "만드는 법",
    cookingTips: "맛있게 만드는 팁",
    comments: "댓글",
    commentsLoading: "댓글을 불러오는 중입니다.",
    firstComment: "첫 댓글을 남겨보세요.",
    commentPlaceholder: "댓글 쓰기",
    commentLoginPlaceholder: "로그인하면 댓글을 쓸 수 있습니다",
    commentSubmit: "댓글 등록",
    relatedRecipes: "관련 레시피",
    footerDescription: "매일의 요리를 더 즐겁게. 가정식, 간단 요리, 인기 레시피를 찾을 수 있는 커뮤니티입니다.",
    footerFind: "찾기",
    footerJoin: "참여하기",
    footerConcept: "콘셉트",
    footerConceptText: "일본 식탁에 어울리는 따뜻하고 쓰기 쉬운 레시피 경험을 지향합니다.",
    postPageTitle: "나만의 레시피 등록하기",
    postPageDesc: "집밥, 간단 요리, 나만의 변형 레시피를 요리히로바에 올려보세요.",
    formLoading: "폼을 불러오는 중입니다.",
    recipeLoading: "레시피를 불러오는 중입니다.",
    recipeNotFound: "레시피를 찾을 수 없습니다",
    recipeNotFoundDesc: "삭제되었거나 URL이 잘못되었을 수 있습니다.",
    goRecipeList: "레시피 목록으로",
  },
  en: {
    brand: "Recipe Hiroba",
    recommended: "Home",
    categories: "Categories",
    ranking: "Ranking",
    column: "Columns",
    post: "Post Recipe",
    mypage: "My Page",
    searchPlaceholder: "Search recipes or ingredients",
    login: "Log in",
    signup: "Sign up",
    logout: "Log out",
    recipes: "Recipes",
    recipeList: "Recipe List",
    recipeSearch: "Recipe Search",
    more: "View more",
    search: "Search",
    welcome: "Welcome",
    heroKicker: "Make everyday meals more fun",
    heroTitle: "What should we cook today?",
    heroDescription: "A community for home cooking, quick meals, lunch boxes, sweets, and shared recipe ideas.",
    todayPick: "Today's Pick",
    recommendedRecipes: "Recommended Recipes",
    bestRecipes: "Best Recipes",
    popular: "Popular",
    todayPopularRecipes: "Today's Popular Recipes",
    todayAccessRanking: "Today's View Ranking",
    categorySearchTitle: "Browse by Cuisine",
    creator: "Creators",
    popularCreators: "Popular Contributors",
    easyFeature: "Quick Cooking Feature",
    quickFeatureTitle: "Meals for busy days in 10 to 20 minutes",
    quickFeatureDescription: "Fast recipes for solo meals, after work dinners, and breakfast.",
    quickFeatureButton: "See quick recipes",
    themedSearch: "Browse by Theme",
    themeTitle: "Recipes for your mood",
    themeBento: "Lunch Box",
    themeBentoDesc: "Mains and prep dishes that still taste good cold",
    themeSolo: "Solo Meals",
    themeSoloDesc: "Easy meals with a short ingredient list",
    themeHealthy: "Healthy",
    themeHealthyDesc: "Vegetable and protein focused recipes",
    themeSweets: "Snacks",
    themeSweetsDesc: "Simple sweets for the weekend",
    guide: "Guide",
    guideTitle: "Cooking Tips",
    guideOne: "Prep work that prevents mistakes",
    guideTwo: "Meal plans from leftovers",
    guideThree: "How to grow popular posts",
    latest: "Latest",
    latestRecipes: "Latest Recipes",
    expertMagazine: "Expert Magazine",
    magazineOne: "How to use seasonal vegetables well",
    magazineTwo: "Change the dashi, change the flavor",
    magazineThree: "Meal prep plans for busy days",
    magazineFour: "Basics for better rice",
    loadedRecipes: "Loading community recipes.",
    loadRecipesFailed: "Could not load community recipes.",
    recipesFoundSuffix: "recipes",
    noRecipesTitle: "No recipes found.",
    noRecipesText: "Try another keyword.",
    categoryDescription: "Find recipes by purpose, from Japanese food and quick meals to sweets and meal prep.",
    rankingTitle: "Popular Recipe Ranking",
    rankingDescription: "Check popular recipes by views, likes, and saves.",
    viewsRanking: "View Ranking",
    likesRanking: "Like Ranking",
    savesRanking: "Save Ranking",
    weeklyPopular: "This Week's Popular Recipes",
    newestPopular: "New Popular Recipes",
    views: "views",
    likes: "likes",
    saves: "saves",
    minutes: "min",
    people: "servings",
    loading: "Loading...",
    loginRequired: "Login required",
    loginRequiredPost: "Please sign up or log in to post a recipe.",
    loginRequiredMypage: "Please log in to manage points and posts.",
    goLogin: "Go to login",
    myPage: "My Page",
    myPageLoading: "Loading My Page.",
    roleAdmin: "Admin",
    pointsOwned: "Points",
    pointHistory: "Point History",
    noPointHistory: "No point history yet.",
    pointSignup: "Sign-up bonus",
    pointRecipePost: "Recipe post points",
    pointLikeMilestone: "Like milestone points",
    myRecipes: "My Posts",
    newPost: "New Post",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this recipe?",
    noMyRecipes: "No posts yet.",
    firstRecipePost: "Post your first recipe",
    adminPanel: "Admin Point Manager",
    adminPanelDesc: "Grant or deduct points for yourself or other members.",
    targetUser: "Target User",
    pointAmount: "Points",
    pointReason: "Reason",
    pointReasonPlaceholder: "Example: event reward, admin adjustment",
    applyPoint: "Apply points",
    pointAdjustSuccess: "Points updated.",
    pointAdjustFailed: "Could not update points.",
    usersLoading: "Loading users.",
    currentUser: "Me",
    basicInfo: "Basic Info",
    recipeEdit: "Edit Recipe",
    title: "Title",
    titlePlaceholder: "Example: Fluffy Oyakodon",
    mainImage: "Main Image",
    imageUrlPlaceholder: "Enter image URL",
    imageNotice: "Direct photo upload will be available after Firebase Storage paid setup. For now, use an image URL.",
    description: "Description",
    descriptionPlaceholder: "Introduce your recipe",
    cookingTime: "Cooking Time",
    servings: "Servings",
    difficulty: "Difficulty",
    category: "Category",
    ingredients: "Ingredients",
    addIngredient: "Add ingredient",
    ingredientName: "Ingredient",
    ingredientAmount: "Amount",
    steps: "Steps",
    addStep: "Add step",
    stepPlaceholder: "Enter cooking step",
    tagsTips: "Tags and Notes",
    tags: "Tags",
    tagsPlaceholder: "Example: quick, Japanese, lunch box",
    tips: "Tips",
    tipsPlaceholder: "Share tips for making it delicious",
    submit: "Submit",
    update: "Update",
    formNeedItems: "Please add at least one ingredient and one step.",
    formPostFailed: "Could not submit the recipe.",
    formLoadRecipe: "Loading recipe.",
    formCheckLogin: "Checking login status.",
    formOnlyMine: "You can only edit your own recipes.",
    formLoadFailed: "Could not load the recipe to edit.",
    authorDefault: "Food Lover",
    authorBioDefault: "Recipe Hiroba contributor.",
    tipsDefault: "Adjust the portions and enjoy cooking.",
    loginHeroTitle: "Make everyday cooking more fun with Recipe Hiroba.",
    loginHeroDesc: "Log in to save favorites, post recipes, and comment.",
    accountFeatures: "Account Features",
    accountFeaturesDesc: "Log in with email and password.",
    loggedIn: "You are logged in",
    backHome: "Back to home",
    nickname: "Nickname",
    email: "Email address",
    password: "Password",
    passwordMin: "At least 6 characters",
    passwordConfirm: "Confirm Password",
    passwordConfirmPlaceholder: "Enter again",
    recoveryQuestion: "Recovery Question",
    recoveryAnswer: "Recovery Answer",
    recoveryAnswerPlaceholder: "Enter your answer",
    signupButton: "Create account",
    loginButton: "Log in",
    forgotPassword: "Forgot password?",
    resetEmailPlaceholder: "Registered email address",
    resetNotice: "Recovery questions are saved for admin verification. The actual reset link is sent to your registered email.",
    sendReset: "Send reset email",
    noAccountGuide: "No account yet? Start with sign up.",
    hasAccountGuide: "Already registered? Switch to log in.",
    nameTooShort: "Nickname must be at least 2 characters.",
    passwordMismatch: "Passwords do not match. Please try again.",
    recoveryRequired: "Please enter your recovery answer.",
    signupDone: "Sign up complete.",
    loginDone: "Logged in.",
    resetSent: "Password reset email sent. Please check your inbox.",
    firebaseRequired: "Firebase setup is required. Check the configuration and try again.",
    categoryCountSuffix: "recipes",
    shareCopied: "URL copied",
    save: "Save",
    share: "Share",
    manageDelete: "Delete",
    banAuthor: "Ban author",
    banConfirm: "Restrict this author?",
    banDone: "Author has been restricted.",
    recipeIngredients: "Ingredients",
    recipeSteps: "Steps",
    cookingTips: "Cooking Tips",
    comments: "Comments",
    commentsLoading: "Loading comments.",
    firstComment: "Write the first comment.",
    commentPlaceholder: "Write a comment",
    commentLoginPlaceholder: "Log in to comment",
    commentSubmit: "Post comment",
    relatedRecipes: "Related Recipes",
    footerDescription: "Make everyday cooking more fun. Browse home cooking, quick meals, and popular recipes.",
    footerFind: "Find",
    footerJoin: "Join",
    footerConcept: "Concept",
    footerConceptText: "We aim for a warm, easy recipe experience for Japanese everyday meals.",
    postPageTitle: "Post your recipe",
    postPageDesc: "Share home cooking, quick recipes, and your own twists with Recipe Hiroba.",
    formLoading: "Loading form.",
    recipeLoading: "Loading recipe.",
    recipeNotFound: "Recipe not found",
    recipeNotFoundDesc: "It may have been deleted or the URL may be incorrect.",
    goRecipeList: "Go to recipe list",
  },
};

const categoryLabels: Record<Language, Record<string, string>> = {
  ja: {},
  ko: {
    和食: "와쇼쿠",
    洋食: "양식",
    中華: "중식",
    韓国料理: "한국 요리",
    お弁当: "도시락",
    一人暮らし: "혼밥",
    時短料理: "간단 요리",
    ダイエット: "다이어트",
    スイーツ: "디저트",
    作り置き: "밑반찬",
    朝ごはん: "아침밥",
    夜食: "야식",
  },
  en: {
    和食: "Japanese",
    洋食: "Western",
    中華: "Chinese",
    韓国料理: "Korean",
    お弁当: "Lunch Box",
    一人暮らし: "Solo Meals",
    時短料理: "Quick Meals",
    ダイエット: "Healthy",
    スイーツ: "Sweets",
    作り置き: "Meal Prep",
    朝ごはん: "Breakfast",
    夜食: "Late Night",
  },
};

const difficultyLabels: Record<Language, Record<string, string>> = {
  ja: {},
  ko: {
    簡単: "쉬움",
    普通: "보통",
    本格: "본격",
  },
  en: {
    簡単: "Easy",
    普通: "Normal",
    本格: "Advanced",
  },
};

const recoveryQuestionLabels: Record<Language, Record<string, string>> = {
  ja: {
    birthday: "誕生日は？",
    university: "卒業した大学は？",
    hometown: "生まれた都市は？",
    favorite_food: "一番好きな食べ物は？",
  },
  ko: {
    birthday: "생일은?",
    university: "내가 졸업한 대학교는?",
    hometown: "태어난 도시는?",
    favorite_food: "가장 좋아하는 음식은?",
  },
  en: {
    birthday: "What is your birthday?",
    university: "Which university did you graduate from?",
    hometown: "Which city were you born in?",
    favorite_food: "What is your favorite food?",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: Record<string, string>;
  categoryName: (category: string) => string;
  difficultyName: (difficulty: string) => string;
  recoveryQuestionName: (questionId: string) => string;
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "ja",
  setLanguage: () => undefined,
  t: labels.ja,
  categoryName: (category) => category,
  difficultyName: (difficulty) => difficulty,
  recoveryQuestionName: (questionId) => recoveryQuestionLabels.ja[questionId] ?? questionId,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ja");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("recipe-hiroba-language");
    if (savedLanguage === "ko" || savedLanguage === "en" || savedLanguage === "ja") {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    localStorage.setItem("recipe-hiroba-language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: labels[language],
      categoryName: (category: string) => categoryLabels[language][category] ?? category,
      difficultyName: (difficulty: string) => difficultyLabels[language][difficulty] ?? difficulty,
      recoveryQuestionName: (questionId: string) =>
        recoveryQuestionLabels[language][questionId] ?? questionId,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
